### ISSUE TITLE
LN-DLC: Do not expect channel to be usable when force-closing

### ISSUE THREAD

**Issue by luckysori** [p2pderivatives/rust-dlc#114]
Here we take the channel lock, but that currently implies that the channel must be usable. We have also considered making it mandatory for the peer to be connected before acquiring the channel lock.

https://github.com/p2pderivatives/rust-dlc/blob/e4ced008cfa8cbaee752751ededa224f3052847c/dlc-manager/src/sub_channel_manager.rs#L707-L719

It does not make sense to enforce those preconditions when force-closing, because force-close should be unilateral and always possible.

More context here: https://github.com/p2pderivatives/rust-lightning/pull/5#issuecomment-1598027322.

**Comment by Tibo-lg** [comment]
Fixed in 34f7334e6f814a25b47f99cdd3cd61f96267dafd
