### ISSUE TITLE
Run Sample failed when start docker

### ISSUE THREAD

**Issue by KunPengRen** [p2pderivatives/rust-dlc#207]
Hi @Devs,
I try to run the test of sample codes, when start to the docker container.
The oracle and oracle-db are both failed, I check the PostgreSQL db container logs, with the below errors:
```
PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-03-19 11:31:10.184 UTC [1] FATAL:  private key file "/certs/db.key" has group or world access
2024-03-19 11:31:10.184 UTC [1] DETAIL:  File must have permissions u=rw (0600) or less if owned by the database user, or permissions u=rw,g=r (0640) or less if owned by root.
2024-03-19 11:31:10.184 UTC [1] LOG:  database system is shut down
```
May I know how to figure out it?

**Comment by Tibo-lg** [comment]
Hi, can you try running the following command before running `docker compose --profile oracle up -d`?
```
docker-compose run oracle-db bash -c "chown postgres:postgres /certs/db.key && chgrp postgres /certs/db.key && chmod 600 /certs/db.key"
```

Let me know if that fixes it or not (if it does I'll add that to the docs).

**Comment by Tibo-lg** [comment]
@bennyhodl not sure what you mean, could you share the error you get and what you run to "manually create `db`" to solve it?

**Comment by h10086733** [comment]
> Hi, can you try running the following command before running `docker compose --profile oracle up -d`? 
`docker compose --profile oracle up -d` 
> 
> ```
> docker-compose run oracle-db bash -c "chown postgres:postgres /certs/db.key && chgrp postgres /certs/db.key && chmod 600 /certs/db.key"
> ```
> 
> Let me know if that fixes it or not (if it does I'll add that to the docs). 

PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-03-25 21:55:52.023 UTC [1] FATAL:  private key file "/certs/db.key" must be owned by the database user or root
2024-03-25 21:55:52.023 UTC [1] LOG:  database system is shut down   
Can you help me answer this?

**Comment by Tibo-lg** [comment]
@h10086733 Can you try running on this branch and tell me if it works for you?
https://github.com/p2pderivatives/rust-dlc/tree/fix/docker-postgres-db

**Comment by h10086733** [comment]
> @h10086733 Can you try running on this branch and tell me if it works for you? https://github.com/p2pderivatives/rust-dlc/tree/fix/docker-postgres-db
PostgreSQL Database directory appears to contain a database; Skipping initialization

2024-03-26 11:28:45.009 UTC [1] FATAL:  database files are incompatible with server
2024-03-26 11:28:45.009 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 16.2 (Debian 16.2-1.pgdg120+2)

**Comment by Tibo-lg** [comment]
> > @h10086733 Can you try running on this branch and tell me if it works for you? https://github.com/p2pderivatives/rust-dlc/tree/fix/docker-postgres-db
> > PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 2024-03-26 11:28:45.009 UTC [1] FATAL: database files are incompatible with server 2024-03-26 11:28:45.009 UTC [1] DETAIL: The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 16.2 (Debian 16.2-1.pgdg120+2)

Please do a `docker compose --profile oracle down -v` and try again (assuming you don't care about the data). You seem to have a leftover volume from a previous.

**Comment by h10086733** [comment]
> > > @h10086733 Can you try running on this branch and tell me if it works for you? https://github.com/p2pderivatives/rust-dlc/tree/fix/docker-postgres-db
> > > PostgreSQL Database directory appears to contain a database; Skipping initialization
> > 
> > 
> > 2024-03-26 11:28:45.009 UTC [1] FATAL: database files are incompatible with server 2024-03-26 11:28:45.009 UTC [1] DETAIL: The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 16.2 (Debian 16.2-1.pgdg120+2)
> 
> Please do a `docker compose --profile oracle down -v` and try again (assuming you don't care about the data). You seem to have a leftover volume from a previous run.

Thank you for your answer, but I seem to have encountered a new problem.

**Comment by Tibo-lg** [comment]
> > > > @h10086733 Can you try running on this branch and tell me if it works for you? https://github.com/p2pderivatives/rust-dlc/tree/fix/docker-postgres-db
> > > > PostgreSQL Database directory appears to contain a database; Skipping initialization
> > > 
> > > 
> > > 2024-03-26 11:28:45.009 UTC [1] FATAL: database files are incompatible with server 2024-03-26 11:28:45.009 UTC [1] DETAIL: The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 16.2 (Debian 16.2-1.pgdg120+2)
> > 
> > 
> > Please do a `docker compose --profile oracle down -v` and try again (assuming you don't care about the data). You seem to have a leftover volume from a previous run.
> 
> Thank you for your answer, but I seem to have encountered a new problem. My environment is in the Ubuntu system under WSL {"level":"info","msg":"ORM initialization starts","time":"2024-03-26T12:03:10Z"} oracle-server | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: hostname resolving error (lookup oracle-db on 127.0.0.11:53: read udp 127.0.0.1:36757-\u003e127.0.0.11:53: read: connection refused)Could not open database.","time":"2024-03-26T12:03:10Z"} oracle-server | {"level":"info","msg":"ORM initialization end","time":"2024-03-26T12:03:10Z"} oracle-server | panic: Could not initialize database.

Which version of docker compose are you using (`docker compose version`)?

**Comment by h10086733** [comment]
> docker compose version

Docker Compose version v2.25.0

**Comment by Tibo-lg** [comment]
If you let it run doesn't the `oracle-server` restart and eventually works?

**Comment by h10086733** [comment]
> If you let it run doesn't the `oracle-server` restart and eventually works?
yes,I'm not sure if my Docker container is in Ubuntu, which is a subsystem of Windows. I tried to change to localhost or 127.0.0.1 but was unable to succeed
oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-26T12:19:10Z"}
oracle-server  | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: hostname resolving error (lookup oracle-db on 127.0.0.11:53: read udp 127.0.0.1:55861-\u003e127.0.0.11:53: read: connection refused)Could not open database.","time":"2024-03-26T12:19:10Z"}
oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-26T12:19:10Z"}
oracle-server  | panic: Could not initialize database.
oracle-server  |

**Comment by Tibo-lg** [comment]
@h10086733 I checked again and I can see a similar log than yours at first:

```
oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-28T07:02:00Z"}
oracle-server  | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: dial e
rror (dial tcp 172.26.0.4:5432: connect: connection refused)Could not open database.","time":"2024-03-28T07:02:0
0Z"}
oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-28T07:02:00Z"}
oracle-server  | panic: Could not initialize database.
oracle-server  | 
oracle-server  | goroutine 1 [running]:
oracle-server  | main.newInitializedOrm(0xc00038e6e0, 0xc00006caa0, 0xc000010130)
oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:143 +0x1b8
oracle-server  | main.NewDefaultOracleAPI(0xc00006caa0, 0xc00038e6e0, 0x0, 0x0)
oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:183 +0x19b
oracle-server  | main.newInitializedRouter(0xc00006caa0, 0xc00038e6e0, 0x0)
oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:157 +0x39
oracle-server  | main.main()
oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:70 +0x189
```

But then the `oracle-db` finishes initializing and eventually the `oracle-server` starts working:

```
oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-28T07:02:01Z"}
oracle-db-1    | 2024-03-28 07:02:01.532 UTC [66] LOG:  statement: ;
oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-28T07:02:01Z"}
oracle-db-1    | 2024-03-28 07:02:01.542 UTC [66] LOG:  execute lrupsc_1_0: SELECT count(*) FROM information_sch
ema.tables WHERE table_schema =  CURRENT_SCHEMA() AND table_name = $1 AND table_type = $2
```

If it's not the case for you can you send a more detailed log including the traces for the `oracle-db` container?

**Comment by h10086733** [comment]
> @h10086733 I checked again and I can see a similar log than yours at first:
> 
> ```
> oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-28T07:02:00Z"}
> oracle-server  | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: dial e
> rror (dial tcp 172.26.0.4:5432: connect: connection refused)Could not open database.","time":"2024-03-28T07:02:0
> 0Z"}
> oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-28T07:02:00Z"}
> oracle-server  | panic: Could not initialize database.
> oracle-server  | 
> oracle-server  | goroutine 1 [running]:
> oracle-server  | main.newInitializedOrm(0xc00038e6e0, 0xc00006caa0, 0xc000010130)
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:143 +0x1b8
> oracle-server  | main.NewDefaultOracleAPI(0xc00006caa0, 0xc00038e6e0, 0x0, 0x0)
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:183 +0x19b
> oracle-server  | main.newInitializedRouter(0xc00006caa0, 0xc00038e6e0, 0x0)
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:157 +0x39
> oracle-server  | main.main()
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:70 +0x189
> ```
> 
> But then the `oracle-db` finishes initializing and eventually the `oracle-server` starts working:
> 
> ```
> oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-28T07:02:01Z"}
> oracle-db-1    | 2024-03-28 07:02:01.532 UTC [66] LOG:  statement: ;
> oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-28T07:02:01Z"}
> oracle-db-1    | 2024-03-28 07:02:01.542 UTC [66] LOG:  execute lrupsc_1_0: SELECT count(*) FROM information_sch
> ema.tables WHERE table_schema =  CURRENT_SCHEMA() AND table_name = $1 AND table_type = $2
> ```
> 
> If it's not the case for you can you send a more detailed log including the traces for the `oracle-db` container?
thanks ,I reinstalled the system and docker. Although I don't know the reason, the problem has been resolved. Thank you again

**Comment by h10086733** [comment]
> @h10086733 I checked again and I can see a similar log than yours at first:
> 
> ```
> oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-28T07:02:00Z"}
> oracle-server  | {"level":"error","msg":"failed to connect to `host=oracle-db user=postgres database=db`: dial e
> rror (dial tcp 172.26.0.4:5432: connect: connection refused)Could not open database.","time":"2024-03-28T07:02:0
> 0Z"}
> oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-28T07:02:00Z"}
> oracle-server  | panic: Could not initialize database.
> oracle-server  | 
> oracle-server  | goroutine 1 [running]:
> oracle-server  | main.newInitializedOrm(0xc00038e6e0, 0xc00006caa0, 0xc000010130)
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:143 +0x1b8
> oracle-server  | main.NewDefaultOracleAPI(0xc00006caa0, 0xc00038e6e0, 0x0, 0x0)
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:183 +0x19b
> oracle-server  | main.newInitializedRouter(0xc00006caa0, 0xc00038e6e0, 0x0)
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:157 +0x39
> oracle-server  | main.main()
> oracle-server  |        /p2pderivatives-oracle/cmd/p2pdoracle/main.go:70 +0x189
> ```
> 
> But then the `oracle-db` finishes initializing and eventually the `oracle-server` starts working:
> 
> ```
> oracle-server  | {"level":"info","msg":"ORM initialization starts","time":"2024-03-28T07:02:01Z"}
> oracle-db-1    | 2024-03-28 07:02:01.532 UTC [66] LOG:  statement: ;
> oracle-server  | {"level":"info","msg":"ORM initialization end","time":"2024-03-28T07:02:01Z"}
> oracle-db-1    | 2024-03-28 07:02:01.542 UTC [66] LOG:  execute lrupsc_1_0: SELECT count(*) FROM information_sch
> ema.tables WHERE table_schema =  CURRENT_SCHEMA() AND table_name = $1 AND table_type = $2
> ```
> 
> If it's not the case for you can you send a more detailed log including the traces for the `oracle-db` container?

Hello, I would like to find the Rust DLC technical discussion group where you can consult about project deployment issues. Is there such a group available?

**Comment by Tibo-lg** [comment]
> Hello, I would like to find the Rust DLC technical discussion group where you can consult about project deployment issues. Is there such a group available?

I don't think there is a specific place for that but feel free to open an issue, if I think it's out of scope I'll let you know.
