### ISSUE TITLE
 At which step is the dlc_message_handler. send_message processing executed? How can the event event in the contract be triggered?

### ISSUE THREAD

**Issue by h10086733** [p2pderivatives/rust-dlc#218]
Offered contract: 7c8482d4c1ea57a50d7e7bfbf1ce4df4410ca1dc58831ed1b880bd36a20c816c
Closed contract: 7f7ae9cb72a09892f73f47f07077860139f4c7f869c0762ec4738fa79d70a532
Outcomes: [["0", "0", "0", "0", "0", "0", "1", "0", "0", "0", "1", "1", "0", "0", "1", "0", "1", "0", "0", "0"]]
PnL: -100000000 sats

I would like to ask, should the contract status change to confirmation status after it is blocked? At which step is the dlc_message_handler. send_message processing executed? How can the event event in the contract be triggered? Can anyone help me answer this? Thank you.

**Comment by h10086733** [comment]
The LDK-sample project handles messages, but there is very little explanation for this project. Can you help improve the usage examples?

**Comment by Tibo-lg** [comment]
> At which step is the dlc_message_handler. send_message processing executed? 

`dlc_message_handler.send_message` is called in multiple places in `cli.rs`. It pushes back messages in a queue which is then emptied by the `get_and_clear_pending_msg` method of `message_handler.rs`, which is called by the `process_events` method of `peer_handler.rs` in LDK.

> The LDK-sample project handles messages, but there is very little explanation for this project. Can you help improve the usage examples?

LDK is indeed used to send and receive messages. It's out of the scope of this project to provide documentation for it though (but there is already a lot of documentation for LDK, I think you can check it and get a better idea of how things work).

**Comment by h10086733** [comment]
I am organizing the offer contract, The execution flowchart of acceptbuffer and listcontracts was used to help me understand DLC, but I encountered an issue and saw dlc_message_handler. send_message (pubkey, offer);

Peer_manager. process_events(); I don't know how to run these two pieces of code specifically?
DLC Contract Process：
https://www.processon.com/view/link/665027cf61f8c171fd1cc881
 message handller
https://www.processon.com/view/link/66502817e57102599635aba7?cid=64cc9c49a433c931b2f90c10

I thought it would be executed immediately, but after adding the log, it was not discovered to be executed. Do I understand where the problem lies? For example, after the accept DLC process ->send_message, does it execute the method in on_accept_message?

**Comment by Tibo-lg** [comment]
> For example, after the accept DLC process ->send_message, does it execute the method in on_accept_message?

It should indeed call `on_accept_message` (or `on_accept_channel` if you are using channels). Otherwise I'm sorry but I don't really understand what is your issue. Maybe you can try having a look at the integration tests in `dlc_manager/tests`, that should help you see how things are expected to be processed.

**Comment by h10086733** [comment]
Sorry, there may be some issues with my description,I added a log to the on_accept_message method, but it was not executed. My contract status has not been changed to confirmation status.Do I need to use any other services besides the Rust dlc project to start?
