### ISSUE TITLE
Publish `0.5.0`

### ISSUE THREAD

**Issue by bennyhodl** [p2pderivatives/rust-dlc#220]
There have been a lot of API changes since `0.4.0`. Is there a release planned soon?

**Comment by Tibo-lg** [comment]
Soon I don't know but yes there is plan to do a release at some point. I'd like at least to get the fixes that are in the lightning experimental branch put in master (almost done). I'd also like to split the manager in two (Manager/ChannelManager), but if there is a need for a release before that I don't mind doing one.

**Comment by Tibo-lg** [comment]
There is nothing `lightning` specific in `master` AFAIK, do you mean the DLC channels? By splitting the manager it should make it easier to not care about it, though I don't think having a feature for it makes sense as it doesn't use any extra dependencies.

**Comment by bennyhodl** [comment]
> There is nothing lightning specific in master AFAIK

For some of the traits, such as `Storage` there is some lightning specific stuff

**Comment by Tibo-lg** [comment]
> For some of the traits, such as `Storage` there is some lightning specific stuff

That's for channels not really lightning, but yes that's exactly why I want to split things so I think we're on the same page :)

**Comment by bennyhodl** [comment]
Circling back this issue, could we get a `0.4.1` release or something similar? Would like to publish some crates as well getting the fixed `use-serde` feature that is now merged would be nice.

**Comment by Tibo-lg** [comment]
Sure I can look into that.

**Comment by Tibo-lg** [comment]
Done
