### ISSUE TITLE
Use `bitcoin::secp256k1` over `secp256k1_zkp`

### ISSUE THREAD

**Issue by bennyhodl** [p2pderivatives/rust-dlc#222]
As a pre-req to https://github.com/p2pderivatives/rust-dlc/issues/221

I don't see a specific reason for using `secp25k1_zkp`

**Comment by Tibo-lg** [comment]
`secp256k1_zkp` is required to use the `ecdsa_adaptor` module so I don't think it's possible to use just `secp256k1`.

**Comment by bennyhodl** [comment]
I think it would be worth while to convert everything besides the adaptor stuff. Ran into a lot of dependency issues when upgrading ₿itcoin with #223

**Comment by Tibo-lg** [comment]
I don't think it's possible, the adaptor signature module uses the types from secp256k1 so if they're not from the same version it won't work.

**Comment by bennyhodl** [comment]
Made a PR #226
