### ISSUE TITLE
spec: Oracle Attestation

### ISSUE THREAD

**Issue by bennyhodl** [p2pderivatives/rust-dlc#239]
The oracle attestation should include the `event_id` and `nb_signatures`

https://github.com/discreetlogcontracts/dlcspecs/blob/master/Messaging.md#the-oracle_attestation-type

**Comment by Tibo-lg** [comment]
Yeah the master branch hasn't been updated to the latest specs. There is a branch that has the necessary changes here: https://github.com/p2pderivatives/rust-dlc/tree/feature/new-oracle-format-regular (but it's quite behind).
