### ISSUE TITLE
Error building sample

### ISSUE THREAD

**Issue by josediegorobles** [p2pderivatives/rust-dlc#48]
I have this error:

`error[E0119]: conflicting implementations of trait `std::hash::Hash` for type `zkp::Tag`
   --> /Users/jdrobpar/.cargo/registry/src/github.com-1ecc6299db9ec823/secp256k1-zkp-sys-0.5.0/src/zkp.rs:478:1
    |
478 | impl_array_newtype!(Tag, c_uchar, 32);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `zkp::Tag`
...
493 | impl hash::Hash for Tag {
    | ----------------------- first implementation here
    |
    = note: this error originates in the macro `impl_array_newtype` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0119]: conflicting implementations of trait `std::hash::Hash` for type `zkp::PedersenCommitment`
   --> /Users/jdrobpar/.cargo/registry/src/github.com-1ecc6299db9ec823/secp256k1-zkp-sys-0.5.0/src/zkp.rs:514:1
    |
514 | impl_array_newtype!(PedersenCommitment, c_uchar, 64);
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `zkp::PedersenCommitment`
...
529 | impl hash::Hash for PedersenCommitment {
    | -------------------------------------- first implementation here
    |
    = note: this error originates in the macro `impl_array_newtype` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0119`.`

Similar problem is here: https://github.com/ElementsProject/rust-elements/issues/112 but I use same workarounds and it didn't change anything.

**Comment by Tibo-lg** [comment]
Can you try to run this?
```bash
cargo generate-lockfile --verbose && cargo update -p secp256k1-sys --precise "0.4.1"
```

I need to update to the latest rust-secp256k1-zkp to completely fix the issue (the minor update to 0.4.2 had a breaking change which caused this issue).
Let me know if that fixes it.

**Comment by Tibo-lg** [comment]
You might also need to run a `cargo clean` before this as well.

**Comment by josediegorobles** [comment]
Thanks! It's running now!
