### ISSUE TITLE
Prune contract state once closed

### ISSUE THREAD

**Issue by Tibo-lg** [p2pderivatives/rust-dlc#61]
At the moment all contract information is kept even after the contract has been closed. It would be better to prune it as to reduce storage size.

**Comment by sosaucily** [comment]
How much data will be pruned about closed contracts? Will it be stored at all?

I was curious about adding a `get_closed_contracts` function on the Storage trait, but if that's not in-line with designs.

**Comment by Tibo-lg** [comment]
You can check #71

**Comment by sosaucily** [comment]
Yes I saw 71, but it wasn't clear to me after just a few short minutes of reverse engineering. :)

**Comment by Tibo-lg** [comment]
You can see here what data is kept: https://github.com/p2pderivatives/rust-dlc/pull/71/files#diff-61de353f28460a060339e2341a70bf27e908bdc165b242cb249fdbaffb4d81feR171-R183

**Comment by sosaucily** [comment]
@Tibo-lg Back to this, would it be reasonable to add a `get_closed_contracts` function along side the others like `get_preclosed_contracts`?

I use it for logging and debugging and tracking of the closed DLCs for now, but perhaps that's not a strong enough use case for including the code.

**Comment by sosaucily** [comment]
https://github.com/p2pderivatives/rust-dlc/blob/7e5e560ae21d91d7ab802c4e1d394b1f81ffbb3d/dlc-manager/src/lib.rs#L147

Here on the storage trait

**Comment by Tibo-lg** [comment]
I don't think it's useful to have it on the trait as the `Manager` will not make use of it, you can just add it to your storage implementation?

**Comment by sosaucily** [comment]
yeah, makes sense. I'll try that! Thanks
